name: Run Selenium Script Every 15 Minutes

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      send_tg_message:
        description: 'Enable sending Telegram notifications (yes/no)'
        required: false
        default: 'no'
        type: string

jobs:
  selenium-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Chrome and Chromedriver
        uses: GoogleChrome/setup-chrome@v3

      - name: Run Python Selenium script
        env:
          SIGNIN_PAGE: ${{ secrets.SIGNIN_PAGE }}
          WORKING_PAGE: ${{ secrets.WORKING_PAGE }}
          OPTIONS_BUTTON_SELECTOR: ${{ secrets.OPTIONS_BUTTON_SELECTOR }}
          SAVE_BUTTON_SELECTOR: ${{ secrets.SAVE_BUTTON_SELECTOR }}
          LOGIN_FIELD_SELECTOR: ${{ secrets.LOGIN_FIELD_SELECTOR }}
          PASSWORD_FIELD_SELECTOR: ${{ secrets.PASSWORD_FIELD_SELECTOR }}
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CLICK_DELAY: ${{ secrets.CLICK_DELAY }}
        run: |
          python main.py

  send_message:
    runs-on: ubuntu-latest
    needs: selenium-job
    steps:
      - name: Check Deployment Status
        id: check_status
        run: echo "Check service status or deployment logs here"
        continue-on-error: true

      - name: Conditionally Send Telegram Message
        if: ${{ steps.check_status.outcome == 'success' && github.event.inputs.send_tg_message == 'yes' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Plays saved"